name: Backend
version: 1.0
main: eu.vironlab.mc.bukkit.BukkitLoader
author: Infinity_dev
depend:
  - SimpleCloud-Plugin
  - SimpleCloud-Permission
loadbefore:
  - SimpleCloud-Plugin
  - SimpleCloud-Permission
commands:
  menu:
    usage: menu
    description: Open the Menu
  gamemode:
    usage: gamemode
    description: Change your Gamemode
    aliases:
      - gm